# Generated by Django 4.0.5 on 2022-06-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateEvent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='')),
                ('summary', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='category',
            field=models.CharField(choices=[('SELECT CATEGORY', 'Select Category'), ('BUSINESS_or_PROFESSIONAL', 'Business_or_Professional'), ('CHARITY', 'Charity'), ('COMMUNITY_or_CULTURE', 'Community_or_Culture'), ('FAMILY_or_EDUCATION', 'Family_or_Education'), ('FASHION_or_BEAUTY', 'Fashion_or_Beauty'), ('FILM_or_ENTERTAINMENT', 'Film_or_Entertainment'), ('FOOD_or_DRINKS', 'Food_or_Drinks'), ('GOVERNMENT_or_POLITICS', 'Government_or_Politics'), ('HEALTH_or_WELLNESS', 'Health_or_Wellness'), ('HOBBIES_or_HOLIDAY', 'Hobbies_or_Holiday'), ('MUSIC_or_LIFESTYLE', 'Music_or_Lifestyle'), ('RELIGION_or_SPIRITUALITY', 'Religion_or_Spirituality'), ('SCIENCE_or_TECH', 'Science_or_Tech')], default='Category', max_length=25),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='type',
            field=models.CharField(choices=[('SELECT TYPE', 'Select Type'), ('CAMP_RETREAT', 'Camp_Retreat'), ('CLASS_TRAINING_WORKSHOP', 'Class_Training_Workshop'), ('CONCERT_PERFORMANCE', 'Concert_Performance'), ('CONFERENCE', 'Conference'), ('CONVENTION', 'Convention'), ('DINNER', 'Dinner'), ('FESTIVAL', 'Festival'), ('GAME_COMPETITION', 'Game_Competition'), ('NETWORKING_EVENT', 'Networking_Event'), ('OTHER', 'Other'), ('SOCIAL_GATHERING', 'Social_Gathering'), ('POLITICAL_RALLY', 'Political_Rally'), ('SEMINAR', 'Seminar')], default='Type', max_length=25),
        ),
    ]
