# Generated by Django 4.0.5 on 2022-06-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateEvent', '0002_moredetails_basicinfo_category_basicinfo_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('General_admission', models.CharField(max_length=50)),
                ('Available_Quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='moredetails',
            name='details',
            field=models.TextField(max_length=1000),
        ),
    ]
