# Generated by Django 4.0.5 on 2022-06-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateEvent', '0003_addtickets_alter_moredetails_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moredetails',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='Event_Image'),
        ),
    ]
