# Generated by Django 4.0.5 on 2022-08-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateEvent', '0004_alter_moredetails_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoreDetails',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='details',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='Event_Image'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='summary',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
