# Generated by Django 4.0.5 on 2022-09-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateEvent', '0005_delete_moredetails_basicinfo_details_basicinfo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='details',
            field=models.TextField(max_length=500),
        ),
    ]
