# Generated by Django 4.0.5 on 2022-09-11 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreateEvent', '0005_delete_moredetails_basicinfo_details_basicinfo_image_and_more'),
        ('EventFinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CreateEvent.basicinfo'),
            preserve_default=False,
        ),
    ]
